services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    command: mix run --no-halt

  frontend:
    image: node:20
    working_dir: /app/frontend
    volumes:
      - ./frontend/frontend:/app/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

