app = "invideoaidemo"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "sin"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "4000"

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
