app = "invideoaifrontend"

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"
